import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <nav className="bg-amber-50 text-amber-900 px-8 py-4">
          <div className="flex justify-center gap-8 font-medium">
            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/order">Order</a>
            <a href="/where-to-buy">Where to Buy</a>
            <a href="/contact">Contact</a>
          </div>
        </nav>

        {/* Page content */}
        <main className="max-w-5xl mx-auto p-8">{children}</main>
      </body>
    </html>
  );
}
