import type { Metadata } from "next";
import Image from "next/image";
import { Grape_Nuts } from "next/font/google";
import "./globals.css";

const grapeNuts = Grape_Nuts({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-grape-nuts",
});

export const metadata: Metadata = {
  title: "Welcome to Hayet's Bakery",
  description: "Generated by Chez Hayet",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grapeNuts.variable} antialiased bg-white text-amber-900`}
      >
        <nav className="bg-[#ffe2d0] text-[#b33730] px-8 py-6">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            {/* Logo */}
            <a href="/" className="flex items-center">
              <Image
                src="/logo.png"
                alt="Chez Hayet logo"
                width={80}
                height={80}
                className="h-10 w-auto"
                priority
              />
            </a>

            {/* Navigation links */}
            <div className="flex-1 flex justify-center gap-10 font-bold text-lg">
              <a href="/" className="hover:underline">
                Home
              </a>
              <a href="/about" className="hover:underline">
                About
              </a>
              <a href="/order" className="hover:underline">
                Order
              </a>
              <a href="/where-to-buy" className="hover:underline">
                Where to Buy
              </a>
              <a href="/contact" className="hover:underline">
                Contact
              </a>
            </div>
          </div>
        </nav>

        {/* Page content */}
        <main className="max-w-5xl mx-auto p-8">{children}</main>
      </body>
    </html>
  );
}
